name: Bukld And Deploy Spring Boot to Aws

on:
  push:
    branches: [ master ]

env:
  PROJECT_NAME: one-bucket
  BUCKET_NAME: one-bucket-bucket
  CODE_DEPLOY_APP_NAME: one-bucket-cd
  DEPLOYMENT_GROUP_NAME: one-bucket-cd-group

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: list file
        run: ls -la
      
      - name: Setup Java JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      # build without test
      - name: Build with Gradle
        run: ./gradlew build -x test
        shell: bash

      - name: Start MySQL
        uses: samin/mysql-action@v1.3
        with:
          host port: 3305
          container port: 3305
          mysql database: 'project'
          mysql user: 'sang'
          mysql password: 'sangsang'

      - name: build with test
        run: ./gradlew test

      - name: Make Zip File
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Cpmfogire AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
          
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Code Deploy
        run: aws deploy create-deployment --application-name $CODE_DEPLOY_APP_NAME --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name $DEPLOYMENT_GROUP_NAME --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip

      - name: Notify Slack on Success
        if: success()
        id: slack-success
        uses: slackapi/slack-github-action@v1.24.0
        with: 
          payload: |
            {
              "channel": "backend-git",
              "attachments" : [
                {
                  "color": "#36a64f",
                  "title" : "${{ github.repository }}",
                  "title_link" : "https://github.com/${{ github.repository }}",
                  "text" : "GitHub Action - to AWS servcer success",
                  "fields": [
                    {  
                      "title": "Repository",
                      "value": "${{ github.repository }}",
                      "short": true
                    },
                    {
                      "title": "Tag",
                      "value": "${{ github.ref_name }}",
                      "short": true
                    }
                  ]
                }
              ]
            }
        env: 
          SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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"
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: Notify Slack on Success
        if: failure()
        id: slack-failure
        uses: slackapi/slack-github-action@v1.24.0
        with: 
          payload: |
            {
              "channel": "backend-git",
              "attachments" : [
                {
                  "color": "#ff0000",
                  "title" : "${{ github.repository }}",
                  "title_link" : "https://github.com/${{ github.repository }}",
                  "text" : "GitHub Action - to AWS servcer failure : X ",
                  "fields": [
                    {  
                      "title": "Repository",
                      "value": "${{ github.repository }}",
                      "short": true
                    },
                    {
                      "title": "Tag",
                      "value": "${{ github.ref_name }}",
                      "short": true
                    }
                  ]
                }
              ]
            }
        env: 
          SLACK_WEBHOOK_URL: "https://hooks.slack.com/services/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"
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        
      
